"""Insert sample Moroccan cities, trips, and media if collections are empty."""

from datetime import datetime, timezone
from typing import Any

from motor.motor_asyncio import AsyncIOMotorDatabase

SEED_CITIES: list[dict[str, Any]] = [
    {
        "slug": "agadir",
        "name": "Agadir",
        "region": "Souss-Massa",
        "description": "Sunny Atlantic resort city with long beach promenade and warm winters.",
        "image": "/static/images/agadir.jpg",
        "coordinates": {"lat": 30.4278, "lng": -9.5981},
        "category": "beach",
        "highlights": ["Agadir Beach", "Souk El Had", "Crocoparc"],
    },
    {
        "slug": "al-hoceima",
        "name": "Al Hoceima",
        "region": "Tanger-Tétouan-Al Hoceïma",
        "description": "Mediterranean pearl with stunning beaches and Rif mountain backdrops.",
        "image": "/static/images/al-hoceima.jpg",
        "coordinates": {"lat": 35.2472, "lng": -3.9322},
        "category": "beach",
        "highlights": ["Quemado Beach", "Al Hoceima National Park"],
    },
    {
        "slug": "asilah",
        "name": "Asilah",
        "region": "Tanger-Tétouan-Al Hoceïma",
        "description": "Artistic coastal town known for its murals and historic Portuguese walls.",
        "image": "/static/images/asilah.jpg",
        "coordinates": {"lat": 35.4667, "lng": -6.0333},
        "category": "city",
        "highlights": ["Medina", "Art Murals", "Ramparts"],
    },
    {
        "slug": "casablanca",
        "name": "Casablanca",
        "region": "Casablanca-Settat",
        "description": "Economic heart with modern architecture and the iconic Hassan II Mosque.",
        "image": "/static/images/casablanca.jpg",
        "coordinates": {"lat": 33.5731, "lng": -7.5898},
        "category": "city",
        "highlights": ["Hassan II Mosque", "Corniche", "Old Medina"],
    },
    {
        "slug": "chefchaouen",
        "name": "Chefchaouen",
        "region": "Tanger-Tétouan-Al Hoceïma",
        "description": "Blue-washed mountain lanes in the Rif. Morocco's most photogenic city.",
        "image": "/static/images/chefchaouen.jpg",
        "coordinates": {"lat": 35.1714, "lng": -5.2697},
        "category": "mountains",
        "highlights": ["Blue Medina", "Ras el-Maa Waterfall", "Rif Mountains"],
    },
    {
        "slug": "dakhla",
        "name": "Dakhla",
        "region": "Dakhla-Oued Ed Dahab",
        "description": "Lagoon paradise for kitesurfing, fishing, and stunning sunsets.",
        "image": "/static/images/dakhla.jpg",
        "coordinates": {"lat": 23.7136, "lng": -15.9355},
        "category": "beach",
        "highlights": ["Dakhla Lagoon", "Kitesurfing", "White Dunes"],
    },
    {
        "slug": "el-jadida",
        "name": "El Jadida",
        "region": "Casablanca-Settat",
        "description": "Seaside heritage with Portuguese flair and a stunning cistern.",
        "image": "/static/images/el-jadida.jpg",
        "coordinates": {"lat": 33.2316, "lng": -8.5007},
        "category": "beach",
        "highlights": ["Portuguese Cistern", "Cité Portugaise", "Beach"],
    },
    {
        "slug": "essaouira",
        "name": "Essaouira",
        "region": "Marrakech-Safi",
        "description": "Coastal town with historic ramparts, fresh seafood, and a windy beach.",
        "image": "/static/images/essaouira.jpg",
        "coordinates": {"lat": 31.5085, "lng": -9.7595},
        "category": "beach",
        "highlights": ["Ramparts", "Port", "Windy Beach"],
    },
    {
        "slug": "fes",
        "name": "Fes",
        "region": "Fès-Meknès",
        "description": "Spiritual and cultural center — home to the world's oldest university.",
        "image": "/static/images/fes.jpg",
        "coordinates": {"lat": 34.0181, "lng": -5.0078},
        "category": "city",
        "highlights": ["Chouara Tannery", "Al-Qarawiyyin", "Bou Inania Madrasa"],
    },
    {
        "slug": "ifrane",
        "name": "Ifrane",
        "region": "Fès-Meknès",
        "description": "Switzerland of Morocco — alpine climate, cedar forests, and ski resort nearby.",
        "image": "/static/images/ifrane.jpg",
        "coordinates": {"lat": 33.5228, "lng": -5.1081},
        "category": "mountains",
        "highlights": ["Cedar Forest", "Lion Statue", "Skiing at Mischliffen"],
    },
    {
        "slug": "marrakech",
        "name": "Marrakech",
        "region": "Marrakech-Safi",
        "description": "Historic red city full of culture, souks, and iconic Jemaa el-Fna square.",
        "image": "/static/images/marrakech.jpg",
        "coordinates": {"lat": 31.6295, "lng": -7.9811},
        "category": "city",
        "highlights": ["Medina", "Jemaa el-Fna", "Majorelle Garden"],
    },
    {
        "slug": "merzouga",
        "name": "Merzouga",
        "region": "Drâa-Tafilalet",
        "description": "Erg Chebbi dunes, camel treks, and unforgettable desert camps.",
        "image": "/static/images/merzouga.jpg",
        "coordinates": {"lat": 31.0967, "lng": -4.0118},
        "category": "desert",
        "highlights": ["Erg Chebbi", "Camel Trek", "Desert Camp"],
    },
    {
        "slug": "ouarzazate",
        "name": "Ouarzazate",
        "region": "Drâa-Tafilalet",
        "description": "Gateway to the desert and cinema capital of Morocco.",
        "image": "/static/images/ouarzazate.jpg",
        "coordinates": {"lat": 30.9189, "lng": -6.8934},
        "category": "desert",
        "highlights": ["Aït Benhaddou", "Atlas Studios", "Draa Valley"],
    },
    {
        "slug": "rabat",
        "name": "Rabat",
        "region": "Rabat-Salé-Kénitra",
        "description": "Elegant capital city by the ocean with UNESCO-listed medina.",
        "image": "/static/images/rabat.jpg",
        "coordinates": {"lat": 34.0209, "lng": -6.8416},
        "category": "city",
        "highlights": ["Kasbah des Oudaias", "Tour Hassan", "Chellah"],
    },
    {
        "slug": "safi",
        "name": "Safi",
        "region": "Marrakech-Safi",
        "description": "Atlantic city famous for its pottery and ancient Portuguese castle.",
        "image": "/static/images/safi.jpg",
        "coordinates": {"lat": 32.2994, "lng": -9.2372},
        "category": "city",
        "highlights": ["Pottery Hill", "Qasr al-Bahr", "National Museum of Ceramics"],
    },
    {
        "slug": "tafraoute",
        "name": "Tafraoute",
        "region": "Souss-Massa",
        "description": "Anti-Atlas oasis town surrounded by striking pink granite mountains.",
        "image": "/static/images/tafraoute.jpg",
        "coordinates": {"lat": 29.7202, "lng": -8.9744},
        "category": "mountains",
        "highlights": ["Painted Rocks", "Ameln Valley", "Anti-Atlas"],
    },
    {
        "slug": "tangier",
        "name": "Tangier",
        "region": "Tanger-Tétouan-Al Hoceïma",
        "description": "Gateway to Africa with coastal charm, cafes, and a storied history.",
        "image": "/static/images/tangier.jpg",
        "coordinates": {"lat": 35.7595, "lng": -5.8340},
        "category": "city",
        "highlights": ["Kasbah", "Cap Spartel", "Grand Socco"],
    },
    {
        "slug": "taroudant",
        "name": "Taroudant",
        "region": "Souss-Massa",
        "description": "Often called the Grandmother of Marrakech, famous for its grand red walls.",
        "image": "/static/images/taroudant.jpg",
        "coordinates": {"lat": 30.4703, "lng": -8.8769},
        "category": "city",
        "highlights": ["City Walls", "Souks", "Palais Claudio Bravo"],
    },
    {
        "slug": "tetouan",
        "name": "Tetouan",
        "region": "Tanger-Tétouan-Al Hoceïma",
        "description": "Andalusian-influenced city with a UNESCO-listed medina.",
        "image": "/static/images/tetouan.jpg",
        "coordinates": {"lat": 35.5889, "lng": -5.3626},
        "category": "city",
        "highlights": ["UNESCO Medina", "Royal Palace", "Andalusian Quarter"],
    },
]

SEED_TRIPS: list[dict[str, Any]] = [
    {
        "title": "Sahara Desert Expedition",
        "city": "Merzouga",
        "price": 2890,
        "duration": 3,
        "tags": ["desert", "nature"],
        "image": "/static/images/merzouga.jpg",
        "description": "Erg Chebbi dunes with a camp night, sunset camel ride, and Berber hospitality.",
        "difficulty": "moderate",
    },
    {
        "title": "Agadir Beach Getaway",
        "city": "Agadir",
        "price": 2100,
        "duration": 4,
        "tags": ["beach", "nature"],
        "image": "/static/images/agadir.jpg",
        "description": "Atlantic breeze, promenade cafés, and optional surf or boat outings.",
        "difficulty": "easy",
    },
    {
        "title": "Marrakech Cultural Immersion",
        "city": "Marrakech",
        "price": 1950,
        "duration": 3,
        "tags": ["culture"],
        "image": "/static/images/marrakech.jpg",
        "description": "Medina craftsmanship, palaces, gardens, and the rhythm of Jemaa el-Fna.",
        "difficulty": "easy",
    },
    {
        "title": "Chefchaouen Blue City Trek",
        "city": "Chefchaouen",
        "price": 1650,
        "duration": 2,
        "tags": ["nature", "culture"],
        "image": "/static/images/chefchaouen.jpg",
        "description": "Rif mountain trails, blue-washed alleys, and waterfall hikes nearby.",
        "difficulty": "moderate",
    },
    {
        "title": "Fes Heritage & Craft Tour",
        "city": "Fes",
        "price": 2200,
        "duration": 3,
        "tags": ["culture"],
        "image": "/static/images/fes.jpg",
        "description": "Explore the tanneries, madrasa, and artisan districts of Morocco's oldest city.",
        "difficulty": "easy",
    },
    {
        "title": "Essaouira Coastal Escape",
        "city": "Essaouira",
        "price": 1800,
        "duration": 2,
        "tags": ["beach", "culture"],
        "image": "/static/images/essaouira.jpg",
        "description": "Windswept ramparts, fresh seafood, and sunset walks by the Atlantic.",
        "difficulty": "easy",
    },
    {
        "title": "Ouarzazate & Kasbahs Road Trip",
        "city": "Ouarzazate",
        "price": 3200,
        "duration": 4,
        "tags": ["desert", "culture"],
        "image": "/static/images/ouarzazate.jpg",
        "description": "Visit Aït Benhaddou, Atlas Studios, and the dramatic Draa Valley.",
        "difficulty": "moderate",
    },
    {
        "title": "Casablanca City Weekend",
        "city": "Casablanca",
        "price": 1700,
        "duration": 2,
        "tags": ["culture"],
        "image": "/static/images/casablanca.jpg",
        "description": "Hassan II Mosque, the Corniche, and modern Moroccan dining.",
        "difficulty": "easy",
    },
    {
        "title": "Tangier Gateway Experience",
        "city": "Tangier",
        "price": 2000,
        "duration": 2,
        "tags": ["culture", "beach"],
        "image": "/static/images/tangier.jpg",
        "description": "The Kasbah, Cap Spartel lighthouse, and legendary café culture.",
        "difficulty": "easy",
    },
    {
        "title": "Ifrane Alpine Retreat",
        "city": "Ifrane",
        "price": 2400,
        "duration": 3,
        "tags": ["nature"],
        "image": "/static/images/ifrane.jpg",
        "description": "Cedar forest walks, monkey sightings, and crisp mountain air.",
        "difficulty": "easy",
    },
    {
        "title": "Rabat Capital Discovery",
        "city": "Rabat",
        "price": 1600,
        "duration": 2,
        "tags": ["culture"],
        "image": "/static/images/rabat.jpg",
        "description": "Kasbah des Oudaias, Tour Hassan, and the royal capital's elegant streets.",
        "difficulty": "easy",
    },
    {
        "title": "Atlas Mountain Hiking",
        "city": "Marrakech",
        "price": 2800,
        "duration": 4,
        "tags": ["nature"],
        "image": "/static/images/default.jpg",
        "description": "Day trips into Toubkal, Ourika Valley, and Berber villages.",
        "difficulty": "hard",
    },
]

SEED_MEDIA: list[dict[str, Any]] = [
    {"title": "Agadir Landscapes",      "type": "image", "url": "/static/images/agadir.jpg",      "category": "agadir",      "tags": ["travel", "morocco"]},
    {"title": "Al Hoceima Landscapes",  "type": "image", "url": "/static/images/al-hoceima.jpg",  "category": "al-hoceima",  "tags": ["travel", "morocco"]},
    {"title": "Asilah Landscapes",      "type": "image", "url": "/static/images/asilah.jpg",      "category": "asilah",      "tags": ["travel", "morocco"]},
    {"title": "Casablanca Landscapes",  "type": "image", "url": "/static/images/casablanca.jpg",  "category": "casablanca",  "tags": ["travel", "morocco"]},
    {"title": "Chefchaouen Landscapes", "type": "image", "url": "/static/images/chefchaouen.jpg", "category": "chefchaouen","tags": ["travel", "morocco"]},
    {"title": "Dakhla Landscapes",      "type": "image", "url": "/static/images/dakhla.jpg",      "category": "dakhla",      "tags": ["travel", "morocco"]},
    {"title": "El Jadida Landscapes",   "type": "image", "url": "/static/images/el-jadida.jpg",   "category": "el-jadida",   "tags": ["travel", "morocco"]},
    {"title": "Essaouira Landscapes",   "type": "image", "url": "/static/images/essaouira.jpg",   "category": "essaouira",   "tags": ["travel", "morocco"]},
    {"title": "Fes Landscapes",         "type": "image", "url": "/static/images/fes.jpg",         "category": "fes",         "tags": ["travel", "morocco"]},
    {"title": "Ifrane Landscapes",      "type": "image", "url": "/static/images/ifrane.jpg",      "category": "ifrane",      "tags": ["travel", "morocco"]},
    {"title": "Marrakech Landscapes",   "type": "image", "url": "/static/images/marrakech.jpg",   "category": "marrakech",   "tags": ["travel", "morocco"]},
    {"title": "Merzouga Landscapes",    "type": "image", "url": "/static/images/merzouga.jpg",    "category": "merzouga",    "tags": ["travel", "morocco"]},
    {"title": "Ouarzazate Landscapes",  "type": "image", "url": "/static/images/ouarzazate.jpg",  "category": "ouarzazate",  "tags": ["travel", "morocco"]},
    {"title": "Rabat Landscapes",       "type": "image", "url": "/static/images/rabat.jpg",       "category": "rabat",       "tags": ["travel", "morocco"]},
    {"title": "Safi Landscapes",        "type": "image", "url": "/static/images/safi.jpg",        "category": "safi",        "tags": ["travel", "morocco"]},
    {"title": "Tafraoute Landscapes",   "type": "image", "url": "/static/images/tafraoute.jpg",   "category": "tafraoute",   "tags": ["travel", "morocco"]},
    {"title": "Tangier Landscapes",     "type": "image", "url": "/static/images/tangier.jpg",     "category": "tangier",     "tags": ["travel", "morocco"]},
    {"title": "Taroudant Landscapes",   "type": "image", "url": "/static/images/taroudant.jpg",   "category": "taroudant",   "tags": ["travel", "morocco"]},
    {"title": "Tetouan Landscapes",     "type": "image", "url": "/static/images/tetouan.jpg",     "category": "tetouan",     "tags": ["travel", "morocco"]},
    {"title": "Zagora Landscapes",      "type": "image", "url": "/static/images/zagora.jpg",      "category": "zagora",      "tags": ["travel", "morocco"]},
]


async def seed_collections_if_empty(db: AsyncIOMotorDatabase) -> None:
    cities_col = db["cities"]
    trips_col = db["trips"]
    media_col = db["media"]
    users_col = db["users"]
    favorites_col = db["favorites"]

    # Only seed cities/trips if empty — never wipe existing user data
    if await cities_col.count_documents({}) == 0:
        await cities_col.insert_many([dict(d) for d in SEED_CITIES])

    if await trips_col.count_documents({}) == 0:
        await trips_col.insert_many([dict(d) for d in SEED_TRIPS])

    # ALWAYS wipe and reseed media to guarantee all 20 cities are present
    await media_col.delete_many({})
    await media_col.insert_many([dict(d) for d in SEED_MEDIA])

    # Ensure indexes exist (safe to re-run — MongoDB ignores duplicates)
    await users_col.create_index("email", unique=True)
    await favorites_col.create_index([("user_id", 1), ("trip_id", 1)], unique=True)
    await media_col.create_index([("type", 1), ("category", 1)])

